# -*- coding: utf-8 -*-
"""medical_qlora_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11scK2RUWSy2TXPA1JCHxOXYAUU9-r1FT
"""

!pip install -q unsloth transformers datasets accelerate peft trl bitsandbytes

import torch
torch.cuda.is_available(), torch.cuda.get_device_name(0)

from datasets import load_dataset

dataset = load_dataset("pubmed_qa", "pqa_labeled", split="train[:2000]")
dataset[0]

def format_example(example):
    question = example["question"]
    context = " ".join(example["context"]["contexts"])
    answer = example["long_answer"]

    text = f"""### Instruction:
Answer the following medical question.

### Question:
{question}

### Context:
{context}

### Response:
{answer}"""
    return {"text": text}

dataset = dataset.map(format_example)
dataset = dataset.remove_columns(dataset.column_names[:-1])

from unsloth import FastLanguageModel
import torch

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/llama-3-8b-bnb-4bit",
    max_seq_length=1024,
    dtype=torch.float16,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj","k_proj","v_proj","o_proj",
                    "gate_proj","up_proj","down_proj"],
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)

from trl import SFTTrainer
from transformers import TrainingArguments

training_args = TrainingArguments(
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    warmup_steps=20,
    max_steps=200,  # increase later if you want better results
    learning_rate=2e-4,
    fp16=True,
    logging_steps=10,
    optim="adamw_8bit",
    weight_decay=0.01,
    lr_scheduler_type="linear",
    seed=3407,
    output_dir="medical-qlora-output",
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=1024,
    args=training_args,
)

trainer.train()

model.save_pretrained("medical_lora_adapter")
tokenizer.save_pretrained("medical_lora_adapter")

from google.colab import files
import shutil

shutil.make_archive("medical_lora_adapter", 'zip', "medical_lora_adapter")
files.download("medical_lora_adapter.zip")

FastLanguageModel.for_inference(model)

prompt = """### Instruction:
Answer the following medical question.

### Question:
What are common symptoms of asthma?

### Response:
"""

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

outputs = model.generate(
    **inputs,
    max_new_tokens=200,
    temperature=0.7,
    top_p=0.9,
)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))